kind: pipeline
type: exec
name: default
#foo

clone:
  disable: true

steps:
  - name: initializing dev environment
    commands:
      - cd /tmp/checkout
      - whoami
      - gem install bundler
      - bundle install
  - name: run unit tests
    commands:
      - cd /tmp/checkout
      - bundle exec rake test
